name: Autodocs
on: [ push ]
jobs:
  Update-Config-Examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          commit_message: Automatic update README.md using content from src/test/resources/config